### ISSUE TITLE
Fix this

### ISSUE THREAD

**Issue by priyankarpal** [bytemakers/.github#1]
banner image not showing.

![Screenshot from 2023-02-03 15-48-21](https://user-images.githubusercontent.com/88102392/216575579-57c31d8c-fcb8-411f-a16d-be3d3acfc6ef.png)

**Comment by devarshishimpi** [comment]
Thanks for sharing. Somehow Github won't show the image from the repo itself. I hope it's fixed now :))

<img width="1452" alt="Screenshot 2023-02-04 at 4 40 42 PM" src="https://user-images.githubusercontent.com/43378923/216764033-35e27cde-4242-42fc-825d-9e1c272b6c82.png">

**Comment by Manikanta528** [comment]
again it's broken
<img width="633" alt="Screenshot 2023-08-19 at 12 17 34 PM" src="https://github.com/bytemakers/.github/assets/62022514/129cc9bc-eb99-4dd1-ac0c-96fa65b1eb40">
